### PR TITLE
tests: Add tests for list method sorting

### LINKED ISSUE #11: Repository List Method Tests
Testing `BaseEloquentRepository` is abstract so consider using 
`$this->getMockForAbstractClass('AbstractClass');`

Should include the following:

- [x] It can sort in `ascending` order
- [x] It can sort in `desc` order
- [x] It should `fail` when a random string is passed as the sort argument
- [ ] ~~It should `fail` when a random string is passed to the orderBy argument~~

Should also consider a test with passing no arguments and removing them from the repository specific tests ?

### PR DESCRIPTION
**Pull request by cbj4074**
Fixes #11

### CODE REVIEW

File: tests/Unit/Repositories/ProductTest.php [hunk 1]
```diff
@@ -4,53 +4,39 @@
...
     {
-        $product = $this->createProduct();
+        $product = $this->create();
 
         $this->assertNotNull($product, 'Product IS null');
     }
 
     /** @test */
     public function itCanListAllTheProducts()
     {
```
Comment (poppabear8883) [inline tests/Unit/Repositories/ProductTest.php]: This can be added to the test case ?

File: tests/Unit/Repositories/ProductTest.php [hunk 2]
```diff
@@ -4,53 +4,39 @@
...
+        $n = 3;
+
+        $this->createMany($n);
 
-        $this->assertCount(3, $this->repo->list());
+        $this->assertCount($n, $this->repo->list());
     }
 
     /** @test */
     public function itCanFindAProductByItsId()
```
Comment (poppabear8883) [inline tests/Unit/Repositories/ProductTest.php]: this also can be added to the test case ?

File: tests/Unit/Repositories/RepositoryTestCase.php [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+
+    protected function createMany(int $count = 3): iterable
+    {
+        return factory($this->repo->modelClass(), $count)->create();
+    }
+
+    /** @test */
+    public function itCanListByIdInAscendingOrder()
+    {
+        $products = $this->createMany();
```
Comment (poppabear8883) [inline tests/Unit/Repositories/RepositoryTestCase.php]: refactor this variable name to `$models`

File: tests/Unit/Repositories/RepositoryTestCase.php [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+
+        $ids = $products->sortBy('id')->pluck('id');
+
+        $this->assertEquals($ids, $this->repo->list('id', 'asc')->pluck('id'));
+    }
+
+    /** @test */
+    public function itCanListByIdInDescendingOrder()
+    {
+        $products = $this->createMany();
```
Comment (poppabear8883) [inline tests/Unit/Repositories/RepositoryTestCase.php]: same here, refactor this variable name to `$models`

**Comment by cbj4074** [comment]
I took it a few steps further, as there were a couple other methods that should probably be moved into the base test case.

How's it look now?

File: tests/Unit/Repositories/RepositoryTestCase.php [hunk 5]
```diff
@@ -22,22 +23,56 @@ protected function createMany(int $count = 3): iterable
...
+
+        $this->assertNotNull($model, 'Model IS null');
+    }
+
+    /** @test */
+    public function itCanListAllTheModels()
+    {
+        $n = 3;
+
+        $this->createMany($n);
```
Comment (poppabear8883) [inline tests/Unit/Repositories/RepositoryTestCase.php]: the default for this method is to create 3 models, no need to pass that argument

Comment (cbj4074) [reply tests/Unit/Repositories/RepositoryTestCase.php]: I did that so that if the default ever changes this test won't break. It makes it less brittle.

But this is even slicker:

```php
$this->assertCount($this->createMany()->count(), $this->repo->list());
```

Comment (poppabear8883) [reply tests/Unit/Repositories/RepositoryTestCase.php]: I see, However the default should never change as if a test requires a different value there they just pass it in.

I do like the new proposed assert above. Clean.

**Comment by poppabear8883** [comment]
you probably want to take out the redundant tests in the `ProductImageTest` also

**Comment by poppabear8883** [comment]
and extend the `RepositoryTestCase` on the `ProductImageTest`

**Review by poppabear8883 — DISMISSED** [review]
LGTM

File: src/Repositories/Eloquent/ProductImageRepository.php [hunk 6]
```diff
@@ -76,18 +76,19 @@ public function delete(int $id): bool
...
+        try {
+            $model = $this->findById($id);
 
-        if ($model) {
             if ($model->delete()) {
-                if ($this->filesystem->disk($model->disk)->delete($model->path)) {
-                    $this->db->commit();
-                    return true;
-                }
+                $this->filesystem->disk($model->disk)->delete($model->path);
```
Comment (UncertaintyP) [inline src/Repositories/Eloquent/ProductImageRepository.php]: We must check the return value and abort/rollback if false

**Review by UncertaintyP — CHANGES_REQUESTED** [review]

File: src/Repositories/Eloquent/ProductImageRepository.php (hunk 6 above)
Comment (cbj4074) [reply src/Repositories/Eloquent/ProductImageRepository.php]: Good catch; presumably, nothing in this chain throws an exception?

Comment (cbj4074) [reply src/Repositories/Eloquent/ProductImageRepository.php]: I see your point, now; even though an exception could be thrown on this line, that's not the *only reason* the deletion could fail, e.g., that `delete()` call could return `false` without an exception being thrown. I took a stab at fixing this.

**Review by UncertaintyP — APPROVED** [review]
